{"is_answered": true, "view_count": 101, "tags": ["python", "pandas", "multiprocessing", "python-multiprocessing"], "last_activity_date": 1473954573, "answer_count": 1, "creation_date": 1436806009, "score": 2, "link": "http://stackoverflow.com/questions/31388987/unable-to-send-pandas-dataframe-object-to-sql-when-using-multiprocessing-module", "accepted_answer_id": 39515347, "owner": {"user_id": 4605629, "profile_image": "https://www.gravatar.com/avatar/741edb45b2f1d3e3c3d9555085004ad1?s=128&d=identicon&r=PG&f=1", "user_type": "registered", "reputation": 307, "link": "http://stackoverflow.com/users/4605629/dave", "accept_rate": 79, "display_name": "Dave"}, "title": "Unable to send pandas dataframe object to SQL when using multiprocessing module", "last_edit_date": 1436806343, "question_id": 31388987}