{"owner": {"display_name": "Troy Cooper", "reputation": 3, "profile_image": "https://www.gravatar.com/avatar/1cda20ad26aabfc00856defea8204ec4?s=128&d=identicon&r=PG", "user_id": 6396387, "user_type": "registered", "link": "http://stackoverflow.com/users/6396387/troy-cooper"}, "link": "http://stackoverflow.com/questions/37508052/nameerror-when-using-def-function-in-python", "tags": ["python", "debugging", "typeerror", "nameerror"], "creation_date": 1464512646, "score": 0, "closed_date": 1464513374, "last_edit_date": 1477481382, "is_answered": true, "view_count": 81, "last_activity_date": 1477481382, "question_id": 37508052, "closed_reason": "duplicate", "answer_count": 3, "title": "NameError when using def function in Python"}