{"is_answered": true, "view_count": 91, "tags": ["python", "date", "datetime", "pandas", "dataframe"], "last_activity_date": 1473200149, "answer_count": 1, "creation_date": 1470733971, "score": 1, "link": "http://stackoverflow.com/questions/38846590/python-pandas-producing-error-when-trying-to-access-date-column-on-large-data", "owner": {"user_id": 1626443, "profile_image": "https://www.gravatar.com/avatar/4b512545341f40e0ea191d735034ded9?s=128&d=identicon&r=PG", "user_type": "registered", "reputation": 469, "link": "http://stackoverflow.com/users/1626443/spurious", "accept_rate": 34, "display_name": "Spurious"}, "title": "Python pandas producing error when trying to access &#39;DATE&#39; column on large data set", "last_edit_date": 1473200149, "question_id": 38846590}