{"is_answered": true, "view_count": 56, "tags": ["python", "pandas", "dataframe"], "last_activity_date": 1474397116, "answer_count": 1, "creation_date": 1474395974, "score": 2, "link": "http://stackoverflow.com/questions/39601251/python-error-when-calling-column-data-from-pandas-dataframe", "accepted_answer_id": 39601325, "owner": {"user_id": 5487839, "profile_image": "https://i.stack.imgur.com/4WIG4.png?s=128&g=1", "user_type": "registered", "reputation": 141, "link": "http://stackoverflow.com/users/5487839/carl-pch", "accept_rate": 88, "display_name": "carl_pch"}, "title": "Python error when calling column data from Pandas DataFrame", "last_edit_date": 1474397116, "question_id": 39601251}