{"last_activity_date": 1477685292, "owner": {"display_name": "Meatbot", "reputation": 87, "profile_image": "https://www.gravatar.com/avatar/2231a990c0149e7a5730bd09d2a51365?s=128&d=identicon&r=PG", "user_id": 2111562, "user_type": "registered", "accept_rate": 86, "link": "http://stackoverflow.com/users/2111562/meatbot"}, "is_answered": false, "answer_count": 1, "creation_date": 1475938538, "score": 1, "title": "python-social-auth: AttributeError: &#39;SQLAlchemy&#39; object has no attribute &#39;query&#39; on /complete/vk-oauth2 url", "tags": ["python", "flask", "sqlalchemy", "python-social-auth"], "view_count": 69, "question_id": 39933816, "link": "http://stackoverflow.com/questions/39933816/python-social-auth-attributeerror-sqlalchemy-object-has-no-attribute-query"}