{"owner": {"display_name": "wayne", "reputation": 69, "profile_image": "https://www.gravatar.com/avatar/062800261b8013f15fdfa065b9588e56?s=128&d=identicon&r=PG", "user_id": 957589, "user_type": "registered", "accept_rate": 43, "link": "http://stackoverflow.com/users/957589/wayne"}, "link": "http://stackoverflow.com/questions/40203768/django-manage-py-unable-to-use-python-protobuf-c-implementation", "tags": ["python", "django", "protocol-buffers", "google-protobuf", "manage.py"], "creation_date": 1477231384, "score": 0, "last_edit_date": 1477231827, "is_answered": false, "view_count": 24, "last_activity_date": 1477285609, "question_id": 40203768, "answer_count": 1, "title": "Django manage.py unable to use Python protobuf C++ implementation"}