{"last_activity_date": 1477233086, "owner": {"display_name": "Ablivion", "reputation": 23, "profile_image": "https://i.stack.imgur.com/rLDBv.png?s=128&g=1", "user_id": 5786974, "user_type": "registered", "accept_rate": 100, "link": "http://stackoverflow.com/users/5786974/ablivion"}, "is_answered": false, "answer_count": 0, "creation_date": 1477233086, "score": -1, "title": "Confusing ValueError with &quot;must be x instance&quot; where the passed instance is the correct one", "tags": ["python", "django", "instance"], "view_count": 19, "question_id": 40204072, "link": "http://stackoverflow.com/questions/40204072/confusing-valueerror-with-must-be-x-instance-where-the-passed-instance-is-the"}