{"owner": {"display_name": "vandernath", "reputation": 185, "profile_image": "https://www.gravatar.com/avatar/0a59af0c7872edb9840526ef44e76e1e?s=128&d=identicon&r=PG&f=1", "user_id": 5151880, "user_type": "registered", "accept_rate": 23, "link": "http://stackoverflow.com/users/5151880/vandernath"}, "link": "http://stackoverflow.com/questions/40237207/flask-mail-errno-111-connection-refused", "tags": ["python", "flask", "redis", "celery", "celery-task"], "creation_date": 1477390388, "score": -1, "last_edit_date": 1477395221, "is_answered": false, "view_count": 18, "last_activity_date": 1477395221, "question_id": 40237207, "answer_count": 0, "title": "flask-mail: Errno 111 connection refused"}