{"owner": {"display_name": "shalini", "reputation": 902, "profile_image": "https://www.gravatar.com/avatar/7affb369d10971a395895671a20ce82d?s=128&d=identicon&r=PG&f=1", "user_id": 4069366, "user_type": "registered", "accept_rate": 48, "link": "http://stackoverflow.com/users/4069366/shalini"}, "link": "http://stackoverflow.com/questions/40256600/unable-to-follow-image-as-array-in-python", "tags": ["python", "image", "image-processing"], "creation_date": 1477468281, "score": 2, "last_edit_date": 1477473390, "is_answered": true, "view_count": 38, "last_activity_date": 1477474554, "question_id": 40256600, "answer_count": 1, "title": "Unable to follow image as array in python"}