{"owner": {"display_name": "sds", "reputation": 25237, "profile_image": "https://www.gravatar.com/avatar/75a3213bbcaf279ab4ec2787060c37d4?s=128&d=identicon&r=PG", "user_id": 850781, "user_type": "registered", "accept_rate": 82, "link": "http://stackoverflow.com/users/850781/sds"}, "link": "http://stackoverflow.com/questions/40267192/how-to-keep-iterating-after-an-exception", "tags": ["python", "python-2.7", "iterator"], "creation_date": 1477498167, "score": 2, "last_edit_date": 1477499969, "is_answered": true, "view_count": 49, "last_activity_date": 1477500332, "question_id": 40267192, "accepted_answer_id": 40267415, "answer_count": 1, "title": "How to keep iterating after an exception?"}