{"owner": {"display_name": "Jared Sanchez", "reputation": 28, "profile_image": "https://i.stack.imgur.com/oyDZz.jpg?s=128&g=1", "user_id": 1860833, "user_type": "registered", "accept_rate": 100, "link": "http://stackoverflow.com/users/1860833/jared-sanchez"}, "link": "http://stackoverflow.com/questions/40268396/how-to-catch-function-fails-in-python-with-try-and-except", "tags": ["python", "try-catch"], "creation_date": 1477502182, "score": -1, "is_answered": true, "view_count": 34, "last_activity_date": 1477505521, "question_id": 40268396, "accepted_answer_id": 40268551, "answer_count": 1, "title": "How to catch function fails in python with try and except"}