{"owner": {"display_name": "jramacha", "reputation": 1, "profile_image": "https://www.gravatar.com/avatar/ec19b620862fa1d822a8995f595013dd?s=128&d=identicon&r=PG&f=1", "user_id": 4309651, "user_type": "registered", "accept_rate": 0, "link": "http://stackoverflow.com/users/4309651/jramacha"}, "link": "http://stackoverflow.com/questions/40273250/pyvmomierror-when-calling-relocatevm", "tags": ["python", "vmware", "pyvmomi"], "creation_date": 1477521599, "score": 0, "last_edit_date": 1477531731, "is_answered": false, "view_count": 22, "last_activity_date": 1477553832, "question_id": 40273250, "answer_count": 1, "title": "pyvmomi:error when calling RelocateVM"}