{"owner": {"display_name": "John", "reputation": 6, "profile_image": "https://www.gravatar.com/avatar/21cae0c70e74ad1fe378a6fea6e2780d?s=128&d=identicon&r=PG&f=1", "user_id": 7028440, "user_type": "registered", "link": "http://stackoverflow.com/users/7028440/john"}, "link": "http://stackoverflow.com/questions/40324721/unicodedecodeerror-in-function-python-3-5-2", "tags": ["python", "unicode"], "creation_date": 1477784174, "score": 0, "last_edit_date": 1477784306, "is_answered": true, "view_count": 31, "last_activity_date": 1477795275, "question_id": 40324721, "answer_count": 2, "title": "UnicodeDecodeError in function python 3.5.2"}